DROP TABLE IF EXISTS `gCompileText`;
CREATE TABLE gCompileText (entity int not null AUTO_INCREMENT ,owner char(255),process char(255),activityNum int ,stepNum int ,subStepNum int ,toReplace text, PRIMARY KEY(entity) );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,3 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,5 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,7 ,0 ,'["strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,8 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,9 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,12 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,14 ,0 ,'["boil_vol", "topupvol", "estimated_og", "pretopup_post_mash_og", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,15 ,0 ,'["boil_vol", "pretopup_post_mash_og", "pre_boil_gravity"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,19 ,0 ,'["topupvol", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,20 ,0 ,'["topupvol", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,21 ,0 ,'["estimated_abv", "estimated_fg", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,2 ,7 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'13AG8i9' ,2 ,11 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,3 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,6 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,9 ,0 ,'["strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,10 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,11 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,14 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,16 ,0 ,'["boil_vol", "topupvol", "estimated_og", "pretopup_post_mash_og", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,17 ,0 ,'["boil_vol", "pretopup_post_mash_og", "pre_boil_gravity"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,21 ,0 ,'["topupvol", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,22 ,0 ,'["topupvol", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,23 ,0 ,'["estimated_abv", "estimated_fg", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,1 ,5 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,2 ,7 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'15AG10i11' ,2 ,11 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,4 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,7 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,10 ,0 ,'["strike_temp", "strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,11 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,12 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,15 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,17 ,0 ,'["boil_vol", "topupvol", "estimated_og", "pretopup_post_mash_og", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,18 ,0 ,'["boil_vol", "pretopup_post_mash_og", "pre_boil_gravity"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,22 ,0 ,'["topupvol", "precoolfvvolume", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,23 ,0 ,'["topupvol", "postboil_precool_og", "precoolfvvolume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,25 ,0 ,'["estimated_abv", "estimated_fg", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,1 ,5 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,2 ,7 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'16AG11i12' ,2 ,11 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,4 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,5 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,7 ,0 ,'["strike_temp", "strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,8 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,9 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,12 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,14 ,0 ,'["boil_vol", "topupvol", "estimated_og", "pretopup_post_mash_og", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,15 ,0 ,'["boil_vol", "pretopup_post_mash_og", "pre_boil_gravity"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,19 ,0 ,'["topupvol", "precoolfvvolume", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,20 ,0 ,'["topupvol", "estimated_fg", "postboil_precool_og", "precoolfvvolume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,21 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,22 ,0 ,'["estimated_abv", "estimated_fg", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,1 ,5 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,2 ,7 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'17AG12i13' ,2 ,11 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,9 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,10 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,12 ,0 ,'["strike_temp", "strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,13 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,14 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,17 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,18 ,0 ,'["boil_vol"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,19 ,0 ,'["boil_vol", "topupvol", "estimated_og", "pretopup_post_mash_og", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,20 ,0 ,'["topupvol", "pretopup_post_mash_og", "boil_vol", "pre_boil_gravity"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,23 ,0 ,'["topupvol", "precoolfvvolume", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,24 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,26 ,0 ,'["boil_vol"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,29 ,0 ,'["topupvol", "estimated_fg", "postboil_precool_og", "precoolfvvolume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,30 ,0 ,'["topupvol", "estimated_fg", "postboil_precool_og", "precoolfvvolume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,31 ,0 ,'["estimated_abv", "estimated_fg", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,1 ,5 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,2 ,7 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'19AG16i17' ,2 ,11 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,8 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,9 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,12 ,0 ,'["strike_temp", "strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,13 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,14 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,18 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,20 ,0 ,'["kettle1volume", "kettle1preboilgravity"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,21 ,0 ,'["boil_vol", "kettle2volume", "kettle3volume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,22 ,0 ,'["kettle2preboilgravity", "kettle2volume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,23 ,0 ,'["topupvol", "postboilprecoolgravity", "boil_vol", "preboil_gravity", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,24 ,0 ,'["kettle1evaporation"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,26 ,0 ,'["kettle2evaporation"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,28 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,29 ,0 ,'["kettle3preboilgravity", "kettle3volume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,30 ,0 ,'["kettle3evaporation"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,32 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,34 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,36 ,0 ,'["topupvol", "estimated_fg", "postboil_precool_og", "precoolfvvolume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,37 ,0 ,'["topupvol", "estimated_fg", "postboil_precool_og", "precoolfvvolume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,38 ,0 ,'["estimated_abv", "estimated_fg", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,1 ,5 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,2 ,7 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'20AG17i18' ,2 ,11 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,0 ,6 ,0 ,'["sparge_water"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,0 ,7 ,0 ,'["strike_temp", "strike_temp_5", "sparge_heating_time", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,0 ,8 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,0 ,9 ,0 ,'["sparge_water", "sparge_heating_time"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,0 ,12 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,0 ,20 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'9AG3i4' ,2 ,11 ,0 ,'["primingwater", "primingsugarqty"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,3 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,6 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,7 ,0 ,'["strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,8 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,9 ,0 ,'["sparge_water", "sparge_heating_time"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,12 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,14 ,0 ,'["pretopup_estimated_og", "topupvol", "boil_vol", "pretopup_post_mash_gravity", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,21 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'10AG4i5' ,2 ,9 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,3 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,5 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,7 ,0 ,'["strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,8 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,9 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,12 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,14 ,0 ,'["boil_vol", "topupvol", "estimated_og", "pretopup_post_mash_og", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,20 ,0 ,'["postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,21 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,2 ,5 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'11AG5i6' ,2 ,9 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,3 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,5 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,7 ,0 ,'["strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,8 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,9 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,12 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,14 ,0 ,'["boil_vol", "topupvol", "estimated_og", "pretopup_post_mash_og", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,20 ,0 ,'["topupvol", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,21 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,2 ,6 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7' ,2 ,10 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,3 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,5 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,7 ,0 ,'["strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,8 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,9 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,12 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,14 ,0 ,'["boil_vol", "topupvol", "estimated_og", "pretopup_post_mash_og", "pretopup_estimated_gravity_grain"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,20 ,0 ,'["topupvol", "postboil_precool_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,21 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,2 ,6 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,2 ,10 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,8 ,0 ,'["strike_temp_5"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,9 ,0 ,'["strike_temp_5", "mash_liquid_6"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,12 ,0 ,'["strike_temp", "strike_temp_5", "mash_liquid"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,13 ,0 ,'["strike_temp", "target_mash_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,14 ,0 ,'["sparge_water", "sparge_heating_time", "sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,18 ,0 ,'["sparge_temp"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,20 ,0 ,'["kettle1volume", "kettle1preboilgravity"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,21 ,0 ,'["boil_vol", "kettle2volume", "kettle3volume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,22 ,0 ,'["kettle2preboilgravity", "kettle2volume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,23 ,0 ,'["topupvol", "postboilprecoolgravity", "boil_vol", "preboil_gravity", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,24 ,0 ,'["kettle1evaporation"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,26 ,0 ,'["kettle2evaporation"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,27 ,0 ,'["kettle2evaporation"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,29 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,30 ,0 ,'["kettle3preboilgravity", "kettle3volume"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,31 ,0 ,'["kettle3evaporation"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,33 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,35 ,0 ,'["estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,36 ,0 ,'["postboil_precool_og", "topupvol", "estimated_og", "estimated_fg", "precoolfvvolume", "estimated_abv"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,38 ,0 ,'["estimated_abv", "estimated_fg", "estimated_og"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,1 ,1 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,1 ,2 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,1 ,3 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,1 ,4 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,1 ,5 ,0 ,'["estimated_fg"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,2 ,1 ,0 ,'["polypinqty"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,2 ,2 ,0 ,'["minikegqty"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,2 ,3 ,0 ,'["bottleqty"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,2 ,9 ,0 ,'["num_crown_caps"]' );
INSERT INTO gCompileText VALUES (null ,'test@example.com' ,'21AG18i19' ,2 ,11 ,0 ,'["primingsugartotal", "primingsugarqty", "primingwater"]' );
