DROP TABLE IF EXISTS `gWidgets`;
CREATE TABLE gWidgets (entity int not null AUTO_INCREMENT ,owner char(255),process char(255),activityNum int ,stepNum int ,widgetName char(255),widget char(255),widgetValues text, PRIMARY KEY(entity) );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,1 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,1 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'__adjustedgrav1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,15 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'' ,1 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,15 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'13AG8i9' ,1 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,15 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,15 ,'__adjustedgravInverse1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,16 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,16 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,16 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,17 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,22 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,22 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,22 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,0 ,22 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'15AG10i11' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,16 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,16 ,'__adjustedgravInverse1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,17 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,17 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,17 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,18 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,23 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,23 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,23 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,0 ,23 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'16AG11i12' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,13 ,'__adjustedgravInverse1' ,'invereseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,15 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,19 ,'tempdrainedgravity' ,'gravityTempAdjustment' ,'["tempdraintemp", "tempdraingravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,20 ,'__preRinseAbv' ,'abvCalculation' ,'["__prerinseOg_abv", "__prerinseFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,21 ,'__cooladjustedgravity' ,'gravityTempAdjustment' ,'["__cooltemp", "__coolgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,21 ,'__2additionadjustedgravity' ,'gravityTempAdjustment' ,'["__2additiontemp", "__2additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,0 ,21 ,'2precoolgravity' ,'combineMultipleGravity' ,'["__2gatheredadjustedgravity", "__2additionadjustedgravity", "__2gatheredvol", "__2additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'17AG12i13' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,18 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,18 ,'__adjustedgravInverse1' ,'inverseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,19 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,19 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,19 ,'___combineornot_adjust1' ,'gravityTempAdjustment' ,'["___combineornot_grav1", "___combineornot_temp1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,19 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,19 ,'___combineornot_vol1' ,'gravityVolAdjustment' ,'["___combineornot_adjust1", "preboilgravity", "pretopup_post_mash_og"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,19 ,'___combineornot_predict' ,'combineMultipleGravity' ,'["preboilgravity", "___combineornot_adjust1", "kettle20kettle15vol", "___combineornotplanvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,19 ,'kettle20kettle15vol' ,'add2number' ,'["kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,20 ,'post_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "postadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,20 ,'pre_adjunct_og' ,'gravityTempAdjustment' ,'["preadjuncttemp", "preadjunctgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,24 ,'__2additionadjustedgravity' ,'gravityTempAdjustment' ,'["__2additiontemp", "__2additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,24 ,'2precoolgravity' ,'combineMultipleGravity' ,'["__2gatheredadjustedgravity", "__2additionadjustedgravity", "__2gatheredvol", "__2additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,24 ,'__cooladjustedgravity' ,'gravityTempAdjustment' ,'["__cooltemp", "__coolgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,24 ,'tempdrainedgravity' ,'gravityTempAdjustment' ,'["tempdraintemp", "tempdraingravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,26 ,'__topupvolumereboilAdjusted' ,'gravityTempAdjustment' ,'["__topupvolumereboilTemp", "__topupvolumereboilGravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,26 ,'__topupvolumereboilEndAdjusted' ,'gravityTempAdjustment' ,'["__topupvolumereboilEndTemp", "__topupvolumereboilEndGravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,30 ,'__preRinseAbv' ,'abvCalculation' ,'["__prerinseOg_abv", "__prerinseFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,30 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,30 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,30 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,0 ,30 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'19AG16i17' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,20 ,'__kettle1_adjusted1' ,'gravityTempAdjustment' ,'["__kettle1_temp1", "__kettle1_grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,21 ,'__kettle2_adjusted1' ,'gravityTempAdjustment' ,'["__kettle2_temp1", "__kettle2_grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,21 ,'__adjustedgravInverse1' ,'inverseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,21 ,'__kettle3_adjusted1' ,'gravityTempAdjustment' ,'["__kettle3_temp1", "__kettle3_grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,23 ,'___combineornot_volume' ,'gravityVolAdjustment' ,'["__preboilgravity_2kettles", "__topupgravityadjusted", "kettle1kettle2kettle3volume", "__topupgravityrequired"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,23 ,'preboilgravity_3kettles' ,'combineMultipleGravity' ,'["preboilgravity_2kettles", "__kettle3_adjusted1", "kettle1kettle2volume", "kettle3volume"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,23 ,'___kettle3volumetouse' ,'gravityVolAdjustment' ,'["preboilgravity_2kettles", "__Kettle3_adjusted1", "kettle1kettle2volume", "postboilprecoolgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,23 ,'__topupgravityadjusted' ,' gravityTempAdjustment' ,'["__topupgravity", "__topupgravitytemp"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,23 ,'preboilgravity_2kettles' ,'combineMultipleGravity' ,'["__kettle1_adjusted1", "__kettle2_adjusted1", "kettle1volume", "kettle2volume"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,34 ,'__2additionadjustedgravity' ,'gravityTempAdjustment' ,'["__2additiontemp", "__2additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,34 ,'2precoolgravity' ,'combineMultipleGravity' ,'["__2gatheredadjustedgravity", "__2additionadjustedgravity", "__2gatheredvol", "__2additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,34 ,'__cooladjustedgravity' ,'gravityTempAdjustment' ,'["__cooltemp", "__coolgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,34 ,'tempdrainedgravity' ,'gravityTempAdjustment' ,'["tempdraintemp", "tempdraingravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,37 ,'__preRinseAbv' ,'abvCalculation' ,'["__prerinseOg_abv", "__prerinseFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,37 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,37 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,37 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,0 ,37 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'20AG17i18' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'10AG4i5' ,0 ,20 ,'__adjustedgrav2' ,'gravityTempAdjustment' ,'["__temp2", "__grav2"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'11AG5i6' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,14 ,'preboilgravity' ,'combineMultipleGravity' ,'["kettle20adjustedgravity", "kettle15adjustedgravity", "kettle20vol", "kettle15vol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,14 ,'kettle15adjustedgravity' ,'gravityTempAdjustment' ,'["kettle15temp", "kettle15gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7' ,1 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,13 ,'__adjustedgrav1' ,'gravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,14 ,'kettle20adjustedgravity' ,'gravityTempAdjustment' ,'["kettle20temp", "kettle20gravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,20 ,'__gatheredadjustedgravity' ,'gravityTempAdjustment' ,'["__gatheredtemp", "__gatheredgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,20 ,'__additionadjustedgravity' ,'gravityTempAdjustment' ,'["__additiontemp", "__additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,20 ,'precoolgravity' ,'combineMultipleGravity' ,'["__gatheredadjustedgravity", "__additionadjustedgravity", "__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,0 ,20 ,'precoolvol' ,'add2numbers' ,'["__gatheredvol", "__additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'12AG6i7tiny' ,1 ,5 ,'__abv' ,'abvCalculation' ,'["__measuredOg_abv", "__measuredFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,20 ,'__kettle1_adjusted1' ,'gravityTempAdjustment' ,'["__kettle1_temp1", "__kettle1_grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,21 ,'__kettle2_adjusted1' ,'gravityTempAdjustment' ,'["__kettle2_temp1", "__kettle2_grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,21 ,'__adjustedgravInverse1' ,'inverseGravityTempAdjustment' ,'["__temp1", "__grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,21 ,'__kettle3_adjusted1' ,'gravityTempAdjustment' ,'["__kettle3_temp1", "__kettle3_grav1"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,23 ,'___combineornot_volume' ,'gravityVolAdjustment' ,'["__preboilgravity_2kettles", "__topupgravityadjusted", "kettle1kettle2kettle3volume", "__topupgravityrequired"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,23 ,'preboilgravity_3kettles' ,'combineMultipleGravity' ,'["preboilgravity_2kettles", "__kettle3_adjusted1", "kettle1kettle2volume", "kettle3volume"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,23 ,'___kettle3volumetouse' ,'gravityVolAdjustment' ,'["preboilgravity_2kettles", "__Kettle3_adjusted1", "kettle1kettle2volume", "postboilprecoolgravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,23 ,'__topupgravityadjusted' ,' gravityTempAdjustment' ,'["__topupgravity", "__topupgravitytemp"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,23 ,'preboilgravity_2kettles' ,'combineMultipleGravity' ,'["__kettle1_adjusted1", "__kettle2_adjusted1", "kettle1volume", "kettle2volume"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,35 ,'__2additionadjustedgravity' ,'gravityTempAdjustment' ,'["__2additiontemp", "__2additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,35 ,'tempdrainedgravity' ,'gravityTempAdjustment' ,'["tempdraintemp", "tempdraingravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,35 ,'2precoolgravity' ,'combineMultipleGravity' ,'["__2gatheredadjustedgravity", "__2additionadjustedgravity", "__2gatheredvol", "__2additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,36 ,'__preRinseAbv' ,'abvCalculation' ,'["__prerinseOg_abv", "__prerinseFg_abv"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,36 ,'__2additionadjustedgravity' ,'gravityTempAdjustment' ,'["__2additiontemp", "__2additiongravity"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,36 ,'fvpretopupadjusted' ,'gravityTempAdjustment' ,'["fvpretopuptemp", "fvpretopupgrav"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,0 ,36 ,'2precoolgravity' ,'combineMultipleGravity' ,'["fvpretopupadjusted", "__2additionadjustedgravity", "fvpretopupvolume", "__2additionvol"]' );
INSERT INTO gWidgets VALUES (null ,'test@example.com' ,'21AG18i19' ,1 ,6 ,'__abv' ,'abvCalculation' ,'["og", "__measuredFg_abv"]' );
