#!/usr/bin/env python2.7
import json
import sys
import IPython
sys.path.append('../../confvillain')
import pyangbind.lib.pybindJSON as pybindJSON
from pyangbind.lib.xpathhelper import YANGPathHelper
from pyangbind.lib.serialise import pybindJSONDecoder
import binding

from binding import brewerslab
ph = YANGPathHelper()
p = brewerslab(path_helper = ph)

def dump(obj=None, filter=False, ignore_opdata=True):
    global p
    if not obj:
        obj = p
    print(pybindJSON.dumps(obj, filter=filter, ignore_opdata=ignore_opdata, mode='ietf'))


print('brewerslab() pynabind instance => p')
print('dump() to provide json object')

IPython.embed(display_banner=False)
